Create ToDo list project on function based
sambeck87/React_To-Do-List pull request #1
Opened 2023-01-17 04:43 UTC by sambeck87

Created cpomponents folder
Add Header file
Add inputTodo file
Add Navbar file
Add TodoConteiner file
Add TodoItem file
Add TodoList file
Add module css
Add styles on App file
Create pages folder
Add About file
Add NotMatch file

2023-01-17 16:50 UTC, Juank628 requested changes
## Changes required
Kindly suggest removing all the unneceary files (logo192.png, logo512.png, etc) These files were created with Create React App, but they are not needed in this project.

Please consider the warning shown in the browser console: "ReactDOM.render is no longer supported in React 18. Use createRoot instead" Try to use createRoot.
### Highlights:
- Good descriptive title ✔️
- Good commits ✔️
- Good Gitflow use ✔️
- App works well ✔️
- All linters passing ✔️

2023-01-17 20:46 UTC, Juank628 approved these changes
<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

Nothing more to say. Lets merge!!!
Highlights
Good descriptive title ✔️
Good commits ✔️
Good Gitflow use ✔️
App works well ✔️
All linters passing ✔️
Professional Readme description ✔️

2023-01-19 16:22 UTC, Balikuddembe requested changes
# Status: Required Changes ♻️
Hi @sambeck87 ,

Good job so far!
There are some issues that you still need to work on to make you project look more pleasant and nice but you are almost there!

## Top Highlights
* No linter errors. ✔️
* Good README file. ✔️
* Correct GitFlow. ✔️
* Good Project UI. ✔️

![190492897-0ac7634e-6ab4-4ef2-bd1e-d82c813fedc7](https://user-images.githubusercontent.com/96051955/213496246-b5eeaf58-b39b-46d9-8926-1b5aae945490.gif)

## Suggested changes
Check the comments under the review.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

- [ ] Kindly look into the live version link to your project. It's currently broken. I get 404 error when trying to open it.
- [ ] I suggest you stop using eslint-disable in your code base.This will help you learn how to solve the eslint errors manually and learn more.ESLint - is a very convenient tool to control code quality

2023-01-19 16:22 UTC, Balikuddembe commented on README.md
> +
* Look into the live link as it is broken.

2023-01-19 16:22 UTC, Balikuddembe commented on src/functionBased/components/InputTodo.js
> +import { FaPlusCircle } from 'react-icons/fa';
* Avoid disabling eslint as this will help you learn how to solve linter errors

2023-01-19 16:22 UTC, Balikuddembe commented on src/functionBased/components/TodoContainer.js
> +import { Route, Routes } from 'react-router-dom';
* Avoid disabling eslint as this will help you learn how to fix find and fix errors and improve on your code quality

2023-01-19 16:22 UTC, Balikuddembe commented on src/functionBased/components/TodoItem.js
> +import React, { useState, useEffect } from 'react';
* Avoid disabling eslint as this will help you learn how to fix find and fix errors and improve on your code quality

2023-01-19 16:22 UTC, Balikuddembe commented on src/functionBased/components/TodosList.js
> +import TodoItem from './TodoItem';
* Avoid disabling eslint as this will help you learn how to fix find and fix errors and improve on your code quality

2023-01-28 01:04 UTC, merged